[platformio]
default_envs = i2c_scan

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  adafruit/Adafruit PWM Servo Driver Library@^3.0.2
  lovyan03/LovyanGFX@^1.2.7

[env:i2c_scan]
build_src_filter =
  +<i2c_scan.cpp>
  -<servo_sweep.cpp>
  -<servo_sweep_multi.cpp>
  -<cute_heart_display.cpp>

[env:servo_sweep]
build_src_filter =
  -<i2c_scan.cpp>
  -<cute_heart_display.cpp>
  +<servo_sweep.cpp>
  -<servo_sweep_multi.cpp>

[env:servo_sweep_multi]
build_src_filter =
  -<i2c_scan.cpp>
  -<cute_heart_display.cpp>
  -<servo_sweep.cpp>
  +<servo_sweep_multi.cpp>

[env:cute_heart_display]
build_src_filter =
  -<i2c_scan.cpp>
  -<servo_sweep.cpp>
  -<servo_sweep_multi.cpp>
  +<cute_heart_display.cpp>
